feat: adds permutation and combination functions
UPCGM-ICPC/UPCGM-Notebook pull request #10
Opened 2024-01-21 22:19 UTC by GabinDDL

I've added access to commands for obtaining permutations and combinations from a given list or number

2024-01-21 23:32 UTC, Yag000 requested changes
Could you please remove the useless white space? We need to keep the notebook as slim as possible for the time being.

2024-01-22 09:59 UTC, GabinDDL commented
> Could you please remove the useless white space? We need to keep the notebook as slim as possible for the time being.

Yes sorry I forgot, it's removed now

2024-01-22 10:00 UTC, Yag000 approved these changes

2024-01-23 14:43 UTC, YanisLcn approved these changes

2024-01-23 15:26 UTC, merged