BellmanFord
UPCGM-ICPC/UPCGM-Notebook pull request #5
Opened 2024-01-21 18:12 UTC by YanisLcn

2024-01-21 18:13 UTC, Yag000 requested changes
It has not been added to the notebook itself, it won't be visible on the pdf

2024-01-21 18:14 UTC, Yag000 requested changes

2024-01-21 18:14 UTC, Yag000 commented on content/graph/BellmanFord.py
> +Description: Computes shortest paths from $start$. Allow negatives-weight cycles
```suggestion
Description: Computes shortest paths from $start$. Allows negative-weight cycles
```

2024-01-21 18:14 UTC, Yag000 commented
> It has not been added to the notebook itself, it won't be visible on the pdf

You can see how it can be achieved [here](https://github.com/UPCGM-ICPC/UPCGM-Notebook/pull/4/files).

2024-01-21 18:34 UTC, Yag000 requested changes

2024-01-21 18:34 UTC, Yag000 commented on content/graph/BellmanFord.py
> +Time: $O(VE)$
```suggestion
* Auhtor: Unknown
* Source: https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm
* Description: Computes shortest paths from $start$. Allows negative-weighted cycles
* Time: $O(VE)$
```
Won't compile without this

2024-01-21 18:38 UTC, Yag000 commented on content/graph/BellmanFord.py
> +* Time: $O(VE)$
```suggestion
* Time: O(VE)
```

This might be the issue

2024-01-21 18:41 UTC, YanisLcn commented on content/graph/BellmanFord.py
> +* Time: $O(VE)$
I think the issue is caused by 'Auhtor' instead of 'Author'

2024-01-21 18:50 UTC, Yag000 requested changes
the code does not work. Testing the code is always welcomed :)

2024-01-21 18:50 UTC, Yag000 commented on content/graph/BellmanFord.py
> +def bellmanFord(graph, start_vertex):
This function does not return anything

2024-01-21 18:50 UTC, Yag000 commented on content/graph/BellmanFord.py
the code does not "compile". Using the correct data structure, `Graph`, and adding this code:
```python
if __name__ == "__main__":
    graph = Graph(5, [(0, 1, 1), (1, 2, 1), (2, 3, 1), (3, 1, -3), (1, 4, 1)])
    bellmanFord(graph, 0)
```
yields this error:
```
Traceback (most recent call last):
  File "/home/yago/Projects/UPCGM-Notebook/content/graph/BellmanFord.py", line 63, in <module>
    bellmanFord(graph, 0)
  File "/home/yago/Projects/UPCGM-Notebook/content/graph/BellmanFord.py", line 46, in bellmanFord
    for _ in range(len(graph.v) - 1):
                   ^^^^^^^^^^^^
TypeError: object of type 'int' has no len()
```

2024-01-21 18:50 UTC, Yag000 commented on content/graph/BellmanFord.py
Furthermore, fixing that error, yields this result:
```
Traceback (most recent call last):
  File "/home/yago/Projects/UPCGM-Notebook/content/graph/BellmanFord.py", line 63, in <module>
    bellmanFord(graph, 0)
  File "/home/yago/Projects/UPCGM-Notebook/content/graph/BellmanFord.py", line 47, in bellmanFord
    for u, v, w in graph.edges:
        ^^^^^^^
TypeError: cannot unpack non-iterable int object
```

2024-01-23 12:28 UTC, YanisLcn commented on content/graph/BellmanFord.py
Added method for that

2024-01-23 15:05 UTC, Yag000 requested changes

2024-01-23 15:05 UTC, Yag000 commented on content/graph/GraphClass.py
> +
Could you remove this empty line

2024-01-23 18:57 UTC, Yag000 commented
Using the same example as [previouly](https://github.com/UPCGM-ICPC/UPCGM-Notebook/pull/5#discussion_r1461052745) I get a completely false result... 

```py
if __name__ == "__main__":
    graph = Graph(5, [(0, 1, 1), (1, 2, 1), (2, 3, 1), (3, 1, -3), (1, 4, 1)])
    print(bellmanFord(graph, 0))
```

result:
```
[0, -inf, -inf, -inf, -inf]
```

2024-01-24 14:03 UTC, Yag000 approved these changes
LGTM

2024-01-24 14:13 UTC, merged